version: "3.9"  # optional since v1.27.0
services:
  nginx1:
    image: nginx1_image1
    ports:
      - "91:80"
    build: 
      context: .
      dockerfile: Dockerfile-nginx1
      
  nginx2:
    image: nginx2_image1
    ports:
      - "92:80"
    build: 
      context: .
      dockerfile: Dockerfile-nginx2
      
  nginxsplash:
    image: nginxsplash_image1
    ports:
      - "90:80"
    build: 
      context: .
      dockerfile: Dockerfile-nginxsplash

  myhaproxy:
    image: myhaproxy_image1
    ports:
      - "80:80"
    build: 
      context: .
      dockerfile: Dockerfile-myhaproxy

  